import { stringify as stringifyYaml } from 'yaml';
import type { Pipeline, PipelineStage } from './parser.js';

export interface GenerateOptions {
  /** Path to pipeline source (used in header and compile-check). */
  pipelineFile?: string;
  /** Generated workflow path (compile-check output + check target). */
  workflowOutput?: string;
  /** compile action ref, e.g. aeswibon/pipeline-compose/compile@master or ./compile */
  compileAction?: string;
  defaultBranch?: string;
  /** Tag prefix for refs/tags/{tagPrefix}* (default v). */
  tagPrefix?: string;
}

const DEFAULT_WORKFLOW_OUTPUT = '.github/workflows/pipeline.yml';
const DEFAULT_COMPILE_ACTION = 'aeswibon/pipeline-compose-compile@master';
const DEFAULT_BRANCH = 'master';
const DEFAULT_TAG_PREFIX = 'v';

function normalizeWorkflowPath(workflow: string): string {
  if (workflow.startsWith('./')) {
    return workflow;
  }
  return `./${workflow}`;
}

function resolveInput(value: string): string {
  return value.replace(
    /\$\{\{\s*context\.([a-z0-9-]+)\.([a-z0-9_]+)\s*\}\}/gi,
    (_, stageId, output) => `\${{ needs.${stageId}.outputs.${output} }}`,
  );
}

function stageJob(stage: PipelineStage): Record<string, unknown> {
  const job: Record<string, unknown> = {
    uses: normalizeWorkflowPath(stage.workflow),
    secrets: 'inherit',
  };

  if (stage.needs?.length) {
    job.needs = stage.needs;
  }
  if (stage.environment) {
    job.environment = stage.environment;
  }
  if (stage.inputs && Object.keys(stage.inputs).length > 0) {
    job.with = Object.fromEntries(
      Object.entries(stage.inputs).map(([k, v]) => [k, resolveInput(v)]),
    );
  }

  return job;
}

function isLocalCompileAction(action: string): boolean {
  return action.startsWith('./');
}

function compileCheckSteps(
  pipelineFile: string,
  workflowOutput: string,
  compileAction: string,
): Record<string, unknown>[] {
  const steps: Record<string, unknown>[] = [{ uses: 'actions/checkout@v6' }];

  if (isLocalCompileAction(compileAction)) {
    steps.push({
      name: 'Verify bundled compile action',
      run: 'bash scripts/verify-bundles.sh',
    });
  }

  steps.push({
    uses: compileAction,
    with: {
      pipeline_file: pipelineFile,
      output: workflowOutput,
      check: 'true',
    },
  });

  return steps;
}

function stageIf(tagPrefix: string, when?: string): string {
  const tagGate = `startsWith(github.ref, 'refs/tags/${tagPrefix}')`;
  if (!when) {
    return tagGate;
  }
  return `${tagGate} && (${when})`;
}

export function generateWorkflow(pipeline: Pipeline, opts: GenerateOptions = {}): string {
  const pipelineFile = opts.pipelineFile ?? `.github/pipelines/${pipeline.name}.yml`;
  const workflowOutput = opts.workflowOutput ?? DEFAULT_WORKFLOW_OUTPUT;
  const compileAction = opts.compileAction ?? DEFAULT_COMPILE_ACTION;
  const defaultBranch = opts.defaultBranch ?? DEFAULT_BRANCH;
  const tagPrefix = opts.tagPrefix ?? DEFAULT_TAG_PREFIX;

  const compileCheckIf =
    `github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/${tagPrefix}')`;

  const jobs: Record<string, unknown> = {
    'compile-check': {
      name: 'Compile check',
      if: compileCheckIf,
      'runs-on': 'ubuntu-latest',
      permissions: {
        contents: 'read',
      },
      steps: compileCheckSteps(pipelineFile, workflowOutput, compileAction),
    },
  };

  for (const stage of pipeline.stages) {
    jobs[stage.id] = {
      ...stageJob(stage),
      if: stageIf(tagPrefix, stage.when),
    };
  }

  const doc = {
    name: 'Pipeline',
    on: {
      push: {
        branches: [defaultBranch],
        tags: [`${tagPrefix}*`],
      },
      pull_request: {},
    },
    permissions: {
      contents: 'write',
      actions: 'write',
    },
    concurrency: {
      group: 'pipeline-${{ github.ref }}',
      'cancel-in-progress': false,
    },
    jobs,
  };

  const header = [
    '# Generated by pipeline-compose — do not edit manually',
    `# Source: ${pipelineFile}`,
    '',
  ].join('\n');

  return `${header}${stringifyYaml(doc)}`;
}
